/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.upc.fib.prop.usParlament.presentation;

import es.upc.fib.prop.usParlament.misc.*;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import java.util.Map;
import java.util.Vector;
import java.util.concurrent.ExecutionException;

/**
 *
 * @author miquel
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView(PresentationController precon) {
        pc = precon;
        initComponents();
        setAlgorithmNames();
        currentCongressNameTextField.setText("");
        currentCongressNameTextField.setEnabled(false);
        argumentTextField.setText("");
        argumentLabel.setText("Nº of comms.:");
        argumentTextField.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainWindow = new javax.swing.JTabbedPane();
        mainView = new javax.swing.JPanel();
        congressManagementView = new javax.swing.JPanel();
        MPTablePanel = new javax.swing.JScrollPane();
        currentMPsTable = new javax.swing.JTable();
        buttonsPanel = new javax.swing.JPanel();
        addMPButton = new javax.swing.JButton();
        modifyMPButton = new javax.swing.JButton();
        deleteMPButton = new javax.swing.JButton();
        loadCongressButton = new javax.swing.JButton();
        saveCongressButton = new javax.swing.JButton();
        newCongressButton = new javax.swing.JButton();
        attrDefPanel = new javax.swing.JScrollPane();
        attrDefinitionsTable = new javax.swing.JTable();
        attrDefinitionsPanel = new javax.swing.JPanel();
        newAttrDefButton = new javax.swing.JButton();
        modifyAttrDefButton = new javax.swing.JButton();
        attrDefinitionsLabel = new javax.swing.JLabel();
        currentCongressLabel = new javax.swing.JLabel();
        hideAttrsButton = new javax.swing.JRadioButton();
        CommunityManagement = new javax.swing.JPanel();
        communitiesPanel = new javax.swing.JPanel();
        labelCommunities = new javax.swing.JLabel();
        labelMPs = new javax.swing.JLabel();
        addMPToCommunityButton = new javax.swing.JButton();
        deleteMPfromCommunityButton = new javax.swing.JButton();
        showMPDataButton = new javax.swing.JButton();
        communitiesTablePanel = new javax.swing.JScrollPane();
        communitiesTable = new javax.swing.JTable();
        MPsInCommuntiyPanel = new javax.swing.JScrollPane();
        MPsInCommunityTable = new javax.swing.JTable();
        newCommButton = new javax.swing.JButton();
        delCommButton = new javax.swing.JButton();
        loadPartitionButton = new javax.swing.JButton();
        savePartitionButton = new javax.swing.JButton();
        algorithmLabel = new javax.swing.JLabel();
        chooseAlgorithmComboBox = new javax.swing.JComboBox();
        argumentLabel = new javax.swing.JLabel();
        argumentTextField = new javax.swing.JTextField();
        calculateCommunitiesButton = new javax.swing.JButton();
        algorithmProgressBar = new javax.swing.JProgressBar();
        newPartitionButton = new javax.swing.JButton();
        CompareView = new javax.swing.JPanel();
        CommunityPanel1 = new javax.swing.JPanel();
        scrollPaneCommunityList1 = new javax.swing.JScrollPane();
        communityList1CommunitiesList = new javax.swing.JList();
        list1Label1 = new javax.swing.JLabel();
        list1Label2 = new javax.swing.JLabel();
        scrollPaneMPList1 = new javax.swing.JScrollPane();
        MPList1Table = new javax.swing.JTable();
        currentLoadedCongressLabel = new javax.swing.JLabel();
        currentCongressNameTextField = new javax.swing.JTextField();
        LoadCongressButton = new javax.swing.JButton();
        CommunityPanel2 = new javax.swing.JPanel();
        scrollPaneCommuntiyList2 = new javax.swing.JScrollPane();
        communityList2CommunitiesList = new javax.swing.JList();
        list2Label1 = new javax.swing.JLabel();
        list2Label2 = new javax.swing.JLabel();
        scrollPaneMPList2 = new javax.swing.JScrollPane();
        MPList2Table = new javax.swing.JTable();
        compareButton = new javax.swing.JButton();
        list1OptionsLabel = new javax.swing.JLabel();
        list1UseCurrentPartitionButton = new javax.swing.JButton();
        list1LoadPartitionButton = new javax.swing.JButton();
        list2OptionsLabel = new javax.swing.JLabel();
        list2UseCurrentPartitionButton = new javax.swing.JButton();
        list2LoadPartitionButton = new javax.swing.JButton();
        currentMPsPanel = new javax.swing.JPanel();
        MPsInCurrentCongressLabel = new javax.swing.JLabel();
        scrollPaneMPsCurrentCongressTable = new javax.swing.JScrollPane();
        MPsCurrentCongressTable = new javax.swing.JTable();
        showSelectedMPInfoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);

        mainWindow.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mainWindowStateChanged(evt);
            }
        });

        javax.swing.GroupLayout mainViewLayout = new javax.swing.GroupLayout(mainView);
        mainView.setLayout(mainViewLayout);
        mainViewLayout.setHorizontalGroup(
            mainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 792, Short.MAX_VALUE)
        );
        mainViewLayout.setVerticalGroup(
            mainViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        mainWindow.addTab("Main Page", mainView);

        MPTablePanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        MPTablePanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        MPTablePanel.setName(""); // NOI18N

        currentMPsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        currentMPsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        currentMPsTable.setName("currentMPsTable"); // NOI18N
        MPTablePanel.setViewportView(currentMPsTable);

        buttonsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        addMPButton.setText("Add MP");
        addMPButton.setName("addMPButton"); // NOI18N
        addMPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMPButtonActionPerformed(evt);
            }
        });

        modifyMPButton.setText("Modify MP");
        modifyMPButton.setName("modifyMPButton"); // NOI18N
        modifyMPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyMPButtonActionPerformed(evt);
            }
        });

        deleteMPButton.setText("Delete MP");
        deleteMPButton.setName("deleteMPButton"); // NOI18N
        deleteMPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMPButtonActionPerformed(evt);
            }
        });

        loadCongressButton.setText("Load Congress");
        loadCongressButton.setName("loadCongressButton"); // NOI18N
        loadCongressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadCongressButtonActionPerformed(evt);
            }
        });

        saveCongressButton.setText("Save Congress");
        saveCongressButton.setName("saveCongressButton"); // NOI18N
        saveCongressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCongressButtonActionPerformed(evt);
            }
        });

        newCongressButton.setText("New Congress");
        newCongressButton.setName("newCongressButton"); // NOI18N
        newCongressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCongressButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsPanelLayout = new javax.swing.GroupLayout(buttonsPanel);
        buttonsPanel.setLayout(buttonsPanelLayout);
        buttonsPanelLayout.setHorizontalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addMPButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(modifyMPButton, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(deleteMPButton, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(loadCongressButton, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(saveCongressButton, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                    .addComponent(newCongressButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        buttonsPanelLayout.setVerticalGroup(
            buttonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addMPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modifyMPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteMPButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(loadCongressButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveCongressButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newCongressButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        attrDefinitionsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Importance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        attrDefinitionsTable.setColumnSelectionAllowed(true);
        attrDefinitionsTable.setName("attrDefinitionsTable"); // NOI18N
        attrDefinitionsTable.getTableHeader().setReorderingAllowed(false);
        attrDefPanel.setViewportView(attrDefinitionsTable);
        attrDefinitionsTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        attrDefinitionsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        newAttrDefButton.setText("New Attr. Def.");
        newAttrDefButton.setName("newAttrDefButton"); // NOI18N
        newAttrDefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAttrDefButtonActionPerformed(evt);
            }
        });

        modifyAttrDefButton.setText("Modify Attr. Def.");
        modifyAttrDefButton.setName("modiftAttrDefButton"); // NOI18N
        modifyAttrDefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyAttrDefButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout attrDefinitionsPanelLayout = new javax.swing.GroupLayout(attrDefinitionsPanel);
        attrDefinitionsPanel.setLayout(attrDefinitionsPanelLayout);
        attrDefinitionsPanelLayout.setHorizontalGroup(
            attrDefinitionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attrDefinitionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(attrDefinitionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modifyAttrDefButton, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(newAttrDefButton, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                .addContainerGap())
        );
        attrDefinitionsPanelLayout.setVerticalGroup(
            attrDefinitionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attrDefinitionsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(newAttrDefButton)
                .addGap(18, 18, 18)
                .addComponent(modifyAttrDefButton)
                .addContainerGap())
        );

        attrDefinitionsLabel.setText("Attribute Definitions:");

        currentCongressLabel.setText("Current Congress' MPs");

        hideAttrsButton.setText("Hide irrelevant attrdefs");
        hideAttrsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hideAttrsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout congressManagementViewLayout = new javax.swing.GroupLayout(congressManagementView);
        congressManagementView.setLayout(congressManagementViewLayout);
        congressManagementViewLayout.setHorizontalGroup(
            congressManagementViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(congressManagementViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(congressManagementViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(congressManagementViewLayout.createSequentialGroup()
                        .addGroup(congressManagementViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(attrDefPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                            .addGroup(congressManagementViewLayout.createSequentialGroup()
                                .addGroup(congressManagementViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(attrDefinitionsLabel)
                                    .addComponent(currentCongressLabel))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attrDefinitionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MPTablePanel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(congressManagementViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hideAttrsButton))
                .addGap(24, 24, 24))
        );
        congressManagementViewLayout.setVerticalGroup(
            congressManagementViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(congressManagementViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentCongressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MPTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(attrDefinitionsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(congressManagementViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(attrDefPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attrDefinitionsPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(congressManagementViewLayout.createSequentialGroup()
                .addComponent(buttonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hideAttrsButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mainWindow.addTab("Congress Management", congressManagementView);
        congressManagementView.getAccessibleContext().setAccessibleName("");

        communitiesPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelCommunities.setText("Communities");

        labelMPs.setText("MPs in community");

        addMPToCommunityButton.setText("Add MP to Community");
        addMPToCommunityButton.setName("addMPtoCommunityButton"); // NOI18N
        addMPToCommunityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMPToCommunityButtonActionPerformed(evt);
            }
        });

        deleteMPfromCommunityButton.setText("Delete MP from Community");
        deleteMPfromCommunityButton.setName("deleteMPfromCommunityButton"); // NOI18N
        deleteMPfromCommunityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteMPfromCommunityButtonActionPerformed(evt);
            }
        });

        showMPDataButton.setText("Show MP Data");
        showMPDataButton.setName("deleteMPfromCommunityButton"); // NOI18N
        showMPDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showMPDataButtonActionPerformed(evt);
            }
        });

        communitiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        communitiesTable.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                communitiesTableCaretPositionChanged(evt);
            }
        });
        communitiesTablePanel.setViewportView(communitiesTable);

        MPsInCommunityTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        MPsInCommuntiyPanel.setViewportView(MPsInCommunityTable);

        newCommButton.setText("New Comm.");
        newCommButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCommButtonActionPerformed(evt);
            }
        });

        delCommButton.setText("Delete Comm.");
        delCommButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delCommButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout communitiesPanelLayout = new javax.swing.GroupLayout(communitiesPanel);
        communitiesPanel.setLayout(communitiesPanelLayout);
        communitiesPanelLayout.setHorizontalGroup(
            communitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(communitiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(communitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelCommunities)
                    .addComponent(communitiesTablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(newCommButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delCommButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(communitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(communitiesPanelLayout.createSequentialGroup()
                        .addComponent(MPsInCommuntiyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(communitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addMPToCommunityButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteMPfromCommunityButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                            .addComponent(showMPDataButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(communitiesPanelLayout.createSequentialGroup()
                        .addComponent(labelMPs)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        communitiesPanelLayout.setVerticalGroup(
            communitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(communitiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(communitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCommunities)
                    .addComponent(labelMPs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(communitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MPsInCommuntiyPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(communitiesPanelLayout.createSequentialGroup()
                        .addGroup(communitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(communitiesPanelLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(addMPToCommunityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteMPfromCommunityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(showMPDataButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE))
                            .addGroup(communitiesPanelLayout.createSequentialGroup()
                                .addComponent(communitiesTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(newCommButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delCommButton)))
                .addContainerGap())
        );

        loadPartitionButton.setText("Load Partition");
        loadPartitionButton.setName("loadPartitionButton"); // NOI18N
        loadPartitionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadPartitionButtonActionPerformed(evt);
            }
        });

        savePartitionButton.setText("Save Partition");
        savePartitionButton.setName("savePartitionButton"); // NOI18N
        savePartitionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePartitionButtonActionPerformed(evt);
            }
        });

        algorithmLabel.setText("Algorithm:");

        chooseAlgorithmComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        chooseAlgorithmComboBox.setName("algorithmChooser"); // NOI18N
        chooseAlgorithmComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseAlgorithmComboBoxActionPerformed(evt);
            }
        });

        argumentLabel.setText("Argument:");

        argumentTextField.setText("jTextField2");
        argumentTextField.setName("algorithmInfoTextBox"); // NOI18N

        calculateCommunitiesButton.setText("Calculate");
        calculateCommunitiesButton.setName("calculateCommunitiesButton"); // NOI18N
        calculateCommunitiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateCommunitiesButtonActionPerformed(evt);
            }
        });

        algorithmProgressBar.setName("algorithmProgressBar"); // NOI18N

        newPartitionButton.setText("New Partition");
        newPartitionButton.setName("loadPartitionButton"); // NOI18N
        newPartitionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPartitionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CommunityManagementLayout = new javax.swing.GroupLayout(CommunityManagement);
        CommunityManagement.setLayout(CommunityManagementLayout);
        CommunityManagementLayout.setHorizontalGroup(
            CommunityManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommunityManagementLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CommunityManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CommunityManagementLayout.createSequentialGroup()
                        .addComponent(communitiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CommunityManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loadPartitionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                            .addComponent(savePartitionButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newPartitionButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(CommunityManagementLayout.createSequentialGroup()
                        .addGroup(CommunityManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(algorithmLabel)
                            .addComponent(argumentLabel))
                        .addGap(2, 2, 2)
                        .addGroup(CommunityManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(algorithmProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(calculateCommunitiesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chooseAlgorithmComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(argumentTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        CommunityManagementLayout.setVerticalGroup(
            CommunityManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommunityManagementLayout.createSequentialGroup()
                .addGroup(CommunityManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CommunityManagementLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(newPartitionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loadPartitionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(savePartitionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CommunityManagementLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(communitiesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(CommunityManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(algorithmLabel)
                    .addComponent(chooseAlgorithmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CommunityManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(argumentLabel)
                    .addComponent(argumentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calculateCommunitiesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(algorithmProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        mainWindow.addTab("Community Management", null, CommunityManagement, "");

        CommunityPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        CommunityPanel1.setMaximumSize(new java.awt.Dimension(167, 275));

        communityList1CommunitiesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        communityList1CommunitiesList.setName("communtiyList1"); // NOI18N
        communityList1CommunitiesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                communityList1CommunitiesListValueChanged(evt);
            }
        });
        scrollPaneCommunityList1.setViewportView(communityList1CommunitiesList);

        list1Label1.setText("List of Communities 1:");

        list1Label2.setText("Communtiy MPs:");

        scrollPaneMPList1.setName("MPsList1"); // NOI18N

        MPList1Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        scrollPaneMPList1.setViewportView(MPList1Table);

        javax.swing.GroupLayout CommunityPanel1Layout = new javax.swing.GroupLayout(CommunityPanel1);
        CommunityPanel1.setLayout(CommunityPanel1Layout);
        CommunityPanel1Layout.setHorizontalGroup(
            CommunityPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommunityPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CommunityPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CommunityPanel1Layout.createSequentialGroup()
                        .addGroup(CommunityPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(list1Label1)
                            .addComponent(list1Label2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CommunityPanel1Layout.createSequentialGroup()
                        .addGroup(CommunityPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrollPaneMPList1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPaneCommunityList1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        CommunityPanel1Layout.setVerticalGroup(
            CommunityPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommunityPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(list1Label1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneCommunityList1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(list1Label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneMPList1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        currentLoadedCongressLabel.setText("Currently loaded congress:");

        currentCongressNameTextField.setText("jTextField1");
        currentCongressNameTextField.setName("currentCongressNameTextField"); // NOI18N

        LoadCongressButton.setText("Load Congress");
        LoadCongressButton.setName("loadCongressButton"); // NOI18N
        LoadCongressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoadCongressButtonActionPerformed(evt);
            }
        });

        CommunityPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        communityList2CommunitiesList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        communityList2CommunitiesList.setName("nameList2"); // NOI18N
        communityList2CommunitiesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                communityList2CommunitiesListValueChanged(evt);
            }
        });
        scrollPaneCommuntiyList2.setViewportView(communityList2CommunitiesList);

        list2Label1.setText("List of Communities 2:");

        list2Label2.setText("Community MPs:");

        scrollPaneMPList2.setName("MPsList2"); // NOI18N

        MPList2Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        scrollPaneMPList2.setViewportView(MPList2Table);

        javax.swing.GroupLayout CommunityPanel2Layout = new javax.swing.GroupLayout(CommunityPanel2);
        CommunityPanel2.setLayout(CommunityPanel2Layout);
        CommunityPanel2Layout.setHorizontalGroup(
            CommunityPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommunityPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CommunityPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CommunityPanel2Layout.createSequentialGroup()
                        .addGroup(CommunityPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(list2Label1)
                            .addComponent(list2Label2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CommunityPanel2Layout.createSequentialGroup()
                        .addGroup(CommunityPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(scrollPaneMPList2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrollPaneCommuntiyList2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        CommunityPanel2Layout.setVerticalGroup(
            CommunityPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommunityPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(list2Label1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneCommuntiyList2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(list2Label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneMPList2, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addContainerGap())
        );

        compareButton.setText("Compare");
        compareButton.setName("compareButton"); // NOI18N
        compareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compareButtonActionPerformed(evt);
            }
        });

        list1OptionsLabel.setText("List 1 options:");

        list1UseCurrentPartitionButton.setText("Use current partition");
        list1UseCurrentPartitionButton.setName("useCurrentPartitionList1Button"); // NOI18N
        list1UseCurrentPartitionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1UseCurrentPartitionButtonActionPerformed(evt);
            }
        });

        list1LoadPartitionButton.setText("Load part. from memory");
        list1LoadPartitionButton.setName("loadPartitionList1Button"); // NOI18N
        list1LoadPartitionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list1LoadPartitionButtonActionPerformed(evt);
            }
        });

        list2OptionsLabel.setText("List 2 options:");

        list2UseCurrentPartitionButton.setText("Use current partition");
        list2UseCurrentPartitionButton.setName("useCurrentPartitionList2Button"); // NOI18N
        list2UseCurrentPartitionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list2UseCurrentPartitionButtonActionPerformed(evt);
            }
        });

        list2LoadPartitionButton.setText("Load part. from memory");
        list2LoadPartitionButton.setName("loadPartitionList2Button"); // NOI18N
        list2LoadPartitionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                list2LoadPartitionButtonActionPerformed(evt);
            }
        });

        MPsInCurrentCongressLabel.setText("MPs in current Congress");

        scrollPaneMPsCurrentCongressTable.setName("MPsInCongressList"); // NOI18N

        MPsCurrentCongressTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrollPaneMPsCurrentCongressTable.setViewportView(MPsCurrentCongressTable);

        showSelectedMPInfoButton.setText("Show Selected MP info");
        showSelectedMPInfoButton.setName("selectedMPInfoButton"); // NOI18N
        showSelectedMPInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showSelectedMPInfoButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout currentMPsPanelLayout = new javax.swing.GroupLayout(currentMPsPanel);
        currentMPsPanel.setLayout(currentMPsPanelLayout);
        currentMPsPanelLayout.setHorizontalGroup(
            currentMPsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentMPsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(currentMPsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPaneMPsCurrentCongressTable, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(currentMPsPanelLayout.createSequentialGroup()
                        .addComponent(MPsInCurrentCongressLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(showSelectedMPInfoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addContainerGap())
        );
        currentMPsPanelLayout.setVerticalGroup(
            currentMPsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(currentMPsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MPsInCurrentCongressLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneMPsCurrentCongressTable, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(showSelectedMPInfoButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout CompareViewLayout = new javax.swing.GroupLayout(CompareView);
        CompareView.setLayout(CompareViewLayout);
        CompareViewLayout.setHorizontalGroup(
            CompareViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompareViewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CommunityPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CommunityPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CompareViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CompareViewLayout.createSequentialGroup()
                        .addComponent(currentLoadedCongressLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(currentCongressNameTextField))
                    .addGroup(CompareViewLayout.createSequentialGroup()
                        .addGroup(CompareViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CompareViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(LoadCongressButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(list1OptionsLabel)
                                .addComponent(list1UseCurrentPartitionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(list1LoadPartitionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                            .addGroup(CompareViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(list2OptionsLabel)
                                .addComponent(list2UseCurrentPartitionButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(list2LoadPartitionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(currentMPsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CompareViewLayout.createSequentialGroup()
                        .addComponent(compareButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(46, 46, 46)))
                .addContainerGap())
        );
        CompareViewLayout.setVerticalGroup(
            CompareViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CompareViewLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CompareViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CompareViewLayout.createSequentialGroup()
                        .addGroup(CompareViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(currentLoadedCongressLabel)
                            .addComponent(currentCongressNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CompareViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CompareViewLayout.createSequentialGroup()
                                .addComponent(LoadCongressButton)
                                .addGap(35, 35, 35)
                                .addComponent(list1OptionsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(list1UseCurrentPartitionButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(list1LoadPartitionButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(list2OptionsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(list2UseCurrentPartitionButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(list2LoadPartitionButton))
                            .addComponent(currentMPsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addComponent(compareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CommunityPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CommunityPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainWindow.addTab("Compare", CompareView);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainWindow)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainWindow, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMPToCommunityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMPToCommunityButtonActionPerformed
        int fila = communitiesTable.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(new JFrame(), "No row selected");
            return;
        }
        String cNumb = (String)communitiesTable.getValueAt(fila,0);
        JFrame jf = new addMPToCommunityWindow(pc, Integer.valueOf(cNumb), this, fila);
        jf.setVisible(true);
        jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);


        // TODO add mp to communtiy button pressed
    }//GEN-LAST:event_addMPToCommunityButtonActionPerformed

    private void deleteMPfromCommunityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMPfromCommunityButtonActionPerformed
        // TODO community management delete mp from communtiy button pressed
        int fila1 = communitiesTable.getSelectedRow();
        if(fila1 == -1){
            JOptionPane.showMessageDialog(new JFrame(), "No row selected");
            return;
        }
        int fila2 = MPsInCommunityTable.getSelectedRow();
        if(fila2 == -1){
            JOptionPane.showMessageDialog(new JFrame(), "No row selected");
            return;
        }
        Integer cNumb = Integer.parseInt((String)communitiesTable.getValueAt(fila1,0));
        State st = State.valueOf((String)MPsInCommunityTable.getValueAt(fila2,0));
        Integer distr = (Integer)MPsInCommunityTable.getValueAt(fila2,1);
        pc.deleteMPFromCommunity(cNumb, st, distr);
        updateMPsInCommunityTable();
    }//GEN-LAST:event_deleteMPfromCommunityButtonActionPerformed

    public void radiobuttonAttrDefButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        updateMPManagementAttrDefinitionTable();;
        updateMPManagementMPTable();
    }


    public void setAlgorithmNames() {
        chooseAlgorithmComboBox.removeAllItems();
        // WHILE YOU CHANGE NAMES YOU HAVE TO CHANGE ALSO DomainController.calculateCommunities(algotithm)!!!
        chooseAlgorithmComboBox.addItem("N Clique Percolation");
        //chooseAlgorithmComboBox.addItem("Four Clique Percolation");
        chooseAlgorithmComboBox.addItem("Louvian");
        chooseAlgorithmComboBox.addItem("Newmann Girvan");
    }

    public void updateMPManagementMPTable()
    {
        JSONObject j = pc.getMPList();
        DefaultTableModel dtm = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        JSONArray ja = (JSONArray)j.getJSONByKey("MPList");
        boolean hide = hideAttrsButton.isSelected();

        //System.out.println(j);

        //Create columns
        JSONObject jattrd = pc.getAttrDefs();
        JSONArray a = ((JSONArray)jattrd.getJSONByKey("Attribute Definitions"));

        dtm.addColumn("State");
        dtm.addColumn("District");



        for(JSON jo:a.getArray()){
            String s =((JSONString)((JSONObject)jo).getJSONByKey("AttrDefName")).getValue();
            String imp =((JSONString)((JSONObject)jo).getJSONByKey("AttrDefImportance")).getValue();

            if(imp.equals("0")) imp = "(N)";
            if(imp.equals("1")) imp = "(L)";
            if(imp.equals("4")) imp = "(M)";
            if(imp.equals("16")) imp = "(H)";
            s = s+imp;
            //System.out.println(imp);
            //System.out.print("hide:"+hide);
            //System.out.println(" imp:"+imp.equals("(N)"));
            if(!(hide && imp.equals("(N)"))){
                dtm.addColumn(s);
                //System.out.println(hide);System.out.println(imp.equals("(N)"));
            }
        }


        for(JSON jo:ja.getArray()){
                
            Map<String,String> ms = ((JSONObject)jo).basicJSONObjectGetInfo();

                Vector<String> row = new Vector<String>();
                for(int cnum=0;cnum<dtm.getColumnCount();cnum++) {
                    String s = dtm.getColumnName(cnum);
                    if(s!="State" && s!= "District") s = s.substring(0,s.length()-3);
                    if (ms.containsKey(s)) {
                        row.add(ms.get(s));
                    }else{
                        row.add("-");
                    }
                }
                dtm.addRow(row);


            }
            
        currentMPsTable.setModel(dtm);
        currentMPsTable.getTableHeader().setReorderingAllowed(false);

    }
    
    public void updateMPManagementAttrDefinitionTable()
    {
        DefaultTableModel adtm = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        adtm.addColumn("AttrDefName");
        adtm.addColumn("AttrDefImportance");

        boolean hide = hideAttrsButton.isSelected();

        JSONObject jotd = pc.getAttrDefs();
        JSONArray jatd = ((JSONArray)jotd.getJSONByKey("Attribute Definitions"));

        for(JSON element:jatd.getArray()){

            Map<String,String> ms = ((JSONObject)element).basicJSONObjectGetInfo();
            Vector<String> row = new Vector<String>();
            boolean noval = false;
            for(int pos = 0;pos<jatd.getArray().size();pos++){
                row.add(ms.get("AttrDefName"));
                String imp = ms.get("AttrDefImportance");
                if(imp.equals("0")) imp = "None";
                else if(imp.equals("1")) imp = "Low";
                else if(imp.equals("4")) imp = "Medium";
                else if(imp.equals("16")) imp = "High";
                else throw new IllegalStateException("UNKNOWN Attribute definition importance");
                row.add(imp);
                if(imp.equals("None")) noval = true;
            }

            if(!(hide && noval)) adtm.addRow(row);

        }

            attrDefinitionsTable.setModel(adtm);
            attrDefinitionsTable.getTableHeader().setReorderingAllowed(false);
    }

    public void updateCommunitiesLists() {
        communityList2CommunitiesList.setListData(new Vector(pc.getCommunityIDs("partition2")));
        communityList1CommunitiesList.setListData(new Vector(pc.getCommunityIDs("partition1")));
        communityList1CommunitiesList.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent listSelectionEvent) {
                updateMPList1Table();
            }
        });
        communityList2CommunitiesList.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent listSelectionEvent) {
                updateMPList2Table();
            }
        });
        updateMPList1Table();
        updateMPList2Table();
    }

    public void updateCommunitiesTable()
    {
        JSONObject j = pc.getMainPartitionSize();
        DefaultTableModel dtm = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        JSONString jNumb = (JSONString) j.getJSONByKey("Number");
        dtm.addColumn("Community number");
        //System.out.println(jNumb.getValue());
        for (int i = 0; i < Integer.valueOf(jNumb.getValue()); i++) {
            JSONString ji = new JSONString(String.valueOf(i));
            Vector<String> value = new Vector<String>();
            value.add(ji.getValue());
            dtm.addRow(value);
        }
        communitiesTable.setModel(dtm);
        communitiesTable.getTableHeader().setReorderingAllowed(false);

        communitiesTable.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent event) {
                updateMPsInCommunityTable();
            }
        });
    }

    private void compareWindowMPShortTable()
    {
        JSONObject j = pc.getShortMPList();
            //MPsCurrentCongressTable
            DefaultTableModel model = (DefaultTableModel)MPsCurrentCongressTable.getModel();
            //DefaultTableModel dtm = new DefaultTableModel();
            DefaultTableModel dtm = new DefaultTableModel(){
                @Override
                public boolean isCellEditable(int row,int column){
                    return false;
                }
            };

            //System.out.println(j);

            JSONArray ja = (JSONArray)j.getJSONByKey("MPList");

            //Create columns
            dtm.addColumn("State");
            dtm.addColumn("District");


            for(JSON jo:ja.getArray()){
                
                Map<String,String> ms = ((JSONObject)jo).basicJSONObjectGetInfo();

                Vector<String> row = new Vector<>();
                for(int pos = 0;pos<ja.getArray().size();pos++){
                    /*String s = dtm.getColumnName(pos);
                    if(ms.containsKey(s)){
                        row.add(ms.get(s));
                    }*/
                    row.add(ms.get("State"));
                    row.add(ms.get("District"));

                }
                
                dtm.addRow(row);
                
            }
            
            MPsCurrentCongressTable.setModel(dtm);
            MPsCurrentCongressTable.getTableHeader().setReorderingAllowed(false);
    }

    public void updateMPsCurrentTable() {
        JSONObject j = pc.getShortMPList();
        DefaultTableModel model = (DefaultTableModel)MPsCurrentCongressTable.getModel();
        DefaultTableModel dtm = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };

        //System.out.println(j);

        JSONArray ja = (JSONArray)j.getJSONByKey("MPList");

        //Create columns
        dtm.addColumn("State");
        dtm.addColumn("District");


        for(JSON jo:ja.getArray()){

            Map<String,String> ms = ((JSONObject)jo).basicJSONObjectGetInfo();

            Vector<String> row = new Vector<>();
            for(int pos = 0;pos<ja.getArray().size();pos++){
                    /*String s = dtm.getColumnName(pos);
                    if(ms.containsKey(s)){
                        row.add(ms.get(s));
                    }*/
                row.add(ms.get("State"));
                row.add(ms.get("District"));

            }

            dtm.addRow(row);

        }

        MPsCurrentCongressTable.setModel(dtm);
        MPsCurrentCongressTable.getTableHeader().setReorderingAllowed(false);
    }

    public void updateMPsInCommunityTable() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("State");
        model.addColumn("District");

        int comrow=communitiesTable.getSelectedRow();

        if(comrow == -1){
            MPsInCommunityTable.setModel(model);
            return;
        }

        int community = Integer.parseInt((String)communitiesTable.getValueAt(comrow,0));



        for (JSONObject mp : pc.getMPsCurrentPartition(community)) {
            Vector row = new Vector();
            row.add(((JSONString)mp.getJSONByKey("State")).getValue());
            row.add(Integer.valueOf(((JSONString)mp.getJSONByKey("District")).getValue()));
            model.addRow(row);
        }
        MPsInCommunityTable.setModel(model);
        MPsInCommunityTable.getTableHeader().setReorderingAllowed(false);
    }

    public void updateCurrentLoadedCongressLabel(String name) {
        currentCongressNameTextField.setText(name);
    }

    public void updateMPList1Table() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("State");
        model.addColumn("District");

        Integer selectedRow = (Integer) communityList1CommunitiesList.getSelectedValue();

        if(selectedRow == null){
            MPList1Table.setModel(model);
            return;
        }

        for (JSONObject mp : pc.getMPsPartition1(selectedRow)) {
            Vector row = new Vector();
            row.add(((JSONString)mp.getJSONByKey("State")).getValue());
            row.add(Integer.valueOf(((JSONString)mp.getJSONByKey("District")).getValue()));
            model.addRow(row);
        }
        MPList1Table.setModel(model);
        MPList1Table.getTableHeader().setReorderingAllowed(false);
    }

    public void updateMPList2Table() {
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("State");
        model.addColumn("District");

        Integer selectedRow = (Integer) communityList2CommunitiesList.getSelectedValue();

        if(selectedRow == null){
            MPList2Table.setModel(model);
            return;
        }

        for (JSONObject mp : pc.getMPsPartition2(selectedRow)) {
            Vector row = new Vector();
            row.add(((JSONString)mp.getJSONByKey("State")).getValue());
            row.add(Integer.valueOf(((JSONString)mp.getJSONByKey("District")).getValue()));
            model.addRow(row);
        }
        MPList2Table.setModel(model);
        MPList2Table.getTableHeader().setReorderingAllowed(false);
    }
    
    private void mainWindowStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mainWindowStateChanged
        // In this function goes the code that needs to be executed when we change the window
        //the winows are numbered 0..n-1 in their order on the top
        //There are implementations of an initialization on the code below
        //System.out.println("CANVI DE PESTANYA " + mainWindow.getSelectedIndex());
        
        
        if(mainWindow.getSelectedIndex()==1){//If we are on the MP management Window
            //////INITIALIZING THE MP TABLE
            updateMPManagementMPTable();
            ///INITIALIZE ATTR DEFINITION TABLE
             updateMPManagementAttrDefinitionTable();
            ///FINISHING ATTR DEFINITION TABLE
        }

        if(mainWindow.getSelectedIndex()==2){//If we are on the Community management Window
            updateCommunitiesTable();
            updateMPsInCommunityTable();
        }
        
        if(mainWindow.getSelectedIndex()==3){//If we are on the compare window
            compareWindowMPShortTable();
            updateCommunitiesLists();
        }
    }//GEN-LAST:event_mainWindowStateChanged

    private void addMPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMPButtonActionPerformed
        JFrame jf = new AddMPWindow(pc,this);
        jf.setVisible(true);
        jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_addMPButtonActionPerformed

    private void modifyMPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyMPButtonActionPerformed
        //System.out.println(currentMPsTable.getSelectedRow());
        int fila = currentMPsTable.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(new JFrame(), "No row selected");
            return;
        }
        //columna 0 estat
        //columna 1 districte
        String state = (String)currentMPsTable.getValueAt(fila,0);
        String district = (String) currentMPsTable.getValueAt(fila, 1);
        //Obtenim els valors dels atributs
        JFrame jf = new ModifyMPWindow(pc,this, State.valueOf(state),Integer.parseInt(district));
        jf.setVisible(true);
        jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.updateMPManagementMPTable();
    }//GEN-LAST:event_modifyMPButtonActionPerformed

    private void deleteMPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteMPButtonActionPerformed
        //System.out.println(currentMPsTable.getSelectedRow());
        int fila = currentMPsTable.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(new JFrame(), "No row selected");
            return;
        }
        //columna 0 estat
        //columna 1 districte
        String state = (String)currentMPsTable.getValueAt(fila,0);
        String district = (String) currentMPsTable.getValueAt(fila, 1);
        pc.deleteMP(State.valueOf(state), Integer.parseInt(district));
        this.updateMPManagementMPTable();
    }//GEN-LAST:event_deleteMPButtonActionPerformed

    private void loadCongressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadCongressButtonActionPerformed
        JFrame jf = new LoadCongressWindow(pc, this);
        jf.setVisible(true);
        jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_loadCongressButtonActionPerformed

    private void saveCongressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCongressButtonActionPerformed
        JFrame jf = new SaveCongressWindow(pc, this);
        jf.setVisible(true);
        jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_saveCongressButtonActionPerformed

    private void newCongressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCongressButtonActionPerformed
        pc.newCongress();
        updateMPManagementAttrDefinitionTable();
        updateMPManagementMPTable();
        updateCurrentLoadedCongressLabel("CongressWithoutName");
    }//GEN-LAST:event_newCongressButtonActionPerformed

    private void newAttrDefButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAttrDefButtonActionPerformed
        JFrame jf = new AddAttributeDefinition(pc,this);
        jf.setVisible(true);
        jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_newAttrDefButtonActionPerformed

    private void modifyAttrDefButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyAttrDefButtonActionPerformed
        int fila = attrDefinitionsTable.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(new JFrame(), "No row selected");
            return;
        }
        String attrName = (String) attrDefinitionsTable.getValueAt(fila,0);
        String initialImp = (String) attrDefinitionsTable.getValueAt(fila,1);
        Object[] possibilities = {"None", "Low", "Medium", "High"};
        String s = (String)JOptionPane.showInputDialog(
                this, "Choose the new importance value",

                "Modifying "+attrName+" definition",
                JOptionPane.PLAIN_MESSAGE,
                null,
                possibilities,
                initialImp);
        if(s==null) return;
        JSONObject jAttrD = new JSONObject();
        JSONString value = new JSONString(attrName);
        jAttrD.addPair("AttrDefName", value);
        JSONString value2 = new JSONString(s);
        jAttrD.addPair("Importance", value2);
        pc.addOrModifyAttrDef(jAttrD);
        updateMPManagementAttrDefinitionTable();
        updateMPManagementMPTable();
    }//GEN-LAST:event_modifyAttrDefButtonActionPerformed

    private void showMPDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showMPDataButtonActionPerformed
        int fila = MPsInCommunityTable.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(new JFrame(), "No row selected");
            return;
        }
        String st = MPsInCommunityTable.getValueAt(fila, 0).toString();
        String d =  MPsInCommunityTable.getValueAt(fila, 1).toString();
        int dt = Integer.parseInt(d);
        JFrame jf = new ShowMPInfoWindow(pc, st, dt);
        jf.setVisible(true);
        jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //System.out.println("Show MP Info");
    }//GEN-LAST:event_showMPDataButtonActionPerformed

    private void showSelectedMPInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int fila = MPsCurrentCongressTable.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(new JFrame(), "No row selected");
            return;
        }
        String st =  MPsCurrentCongressTable.getValueAt(fila, 0).toString();
        String d = MPsCurrentCongressTable.getValueAt(fila, 1).toString();
        int dt = Integer.parseInt(d);
        JFrame jf = new ShowMPInfoWindow(pc, st, dt);
        jf.setVisible(true);
        jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        //System.out.println("Show MP Info");
    }

    private void loadPartitionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadPartitionButtonActionPerformed
        JFrame jf = new LoadPartitionWindow(pc, this, "mainPartition");
        jf.setVisible(true);
        jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_loadPartitionButtonActionPerformed

    private void savePartitionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePartitionButtonActionPerformed
        //TODO
        JFrame jf = new savePartitionWindow(pc);
        jf.setVisible(true);
        jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_savePartitionButtonActionPerformed

    CalculateCommunitiesSwingWorker sw;
    private boolean calculating = false;
    private void calculateCommunitiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateCommunitiesButtonActionPerformed

        String argument = argumentTextField.getText();
        String algorithm = (String)chooseAlgorithmComboBox.getSelectedItem();
        try{
            if(algorithm.equals("Newmann Girvan"))Integer.parseInt(argument);
        }catch(IllegalArgumentException il) {
            JOptionPane.showMessageDialog(new JFrame(), "Unvalid value for the nº of communities");
            return;
        }
        if (calculating) {
            calculateCommunitiesButton.setText("Calculate");
            algorithmProgressBar.setIndeterminate(false);
            sw.cancel(false);
            calculating = false;
        } else {
            calculateCommunitiesButton.setText("Cancel");
            algorithmProgressBar.setIndeterminate(true);
            sw = new CalculateCommunitiesSwingWorker(algorithm, argument);
            sw.execute();
            calculating = true;
        }

    }//GEN-LAST:event_calculateCommunitiesButtonActionPerformed

    private void compareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_compareButtonActionPerformed
        JSONObject jInfo = pc.compareFunction();
        String msg = new String();
        msg = "Best partition: " + jInfo.getJSONByKey("Best partition") + "\n";
        msg += "Best modularity: " + jInfo.getJSONByKey("Best modularity") + "\n";
        msg += "Other modularity: " + jInfo.getJSONByKey("Other modularity") + "\n";
        msg += "Percentage of accuracy: " + jInfo.getJSONByKey("Percentage of accuracy");
        JOptionPane.showMessageDialog(new JFrame(), msg);
    }//GEN-LAST:event_compareButtonActionPerformed

    private void list1UseCurrentPartitionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1UseCurrentPartitionButtonActionPerformed
        pc.setCurrentToPartition1();
        updateCommunitiesLists();
    }//GEN-LAST:event_list1UseCurrentPartitionButtonActionPerformed

    private void list1LoadPartitionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list1LoadPartitionButtonActionPerformed
        JFrame jf = new LoadPartitionWindow(pc, this, "partition1");
        jf.setVisible(true);
        jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_list1LoadPartitionButtonActionPerformed

    private void list2UseCurrentPartitionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list2UseCurrentPartitionButtonActionPerformed
        pc.setCurrentToPartition2();
        updateCommunitiesLists();
    }//GEN-LAST:event_list2UseCurrentPartitionButtonActionPerformed

    private void list2LoadPartitionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_list2LoadPartitionButtonActionPerformed
        JFrame jf = new LoadPartitionWindow(pc, this, "partition2");
        jf.setVisible(true);
        jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_list2LoadPartitionButtonActionPerformed

    private void LoadCongressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoadCongressButtonActionPerformed
        JFrame jf = new LoadCongressWindow(pc, this);
        jf.setVisible(true);
        jf.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_LoadCongressButtonActionPerformed

    private void newPartitionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPartitionButtonActionPerformed
        pc.cleanCommunityManager();
        updateCommunitiesTable();
    }//GEN-LAST:event_newPartitionButtonActionPerformed

    private void newCommButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCommButtonActionPerformed
        pc.addNewCommunity();
        updateCommunitiesTable();
    }//GEN-LAST:event_newCommButtonActionPerformed

    private void delCommButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delCommButtonActionPerformed
        int fila = communitiesTable.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(new JFrame(), "No row selected");
            return;
        }
        Integer cNumb = Integer.valueOf((String) communitiesTable.getValueAt(fila, 0));
        pc.deleteSelectedCommunity(cNumb);
        updateCommunitiesTable();
    }//GEN-LAST:event_delCommButtonActionPerformed

    private void communityList1CommunitiesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_communityList1CommunitiesListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_communityList1CommunitiesListValueChanged

    private void communityList2CommunitiesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_communityList2CommunitiesListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_communityList2CommunitiesListValueChanged

    private void communitiesTableCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_communitiesTableCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_communitiesTableCaretPositionChanged

    private void chooseAlgorithmComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseAlgorithmComboBoxActionPerformed
        // TODO add your handling code here:
        if(chooseAlgorithmComboBox.getSelectedItem() != null && ((String)chooseAlgorithmComboBox.getSelectedItem()).equals("Newmann Girvan")) {
            argumentTextField.setEnabled(true);
        }else{
            argumentTextField.setEnabled(false);
            argumentTextField.setText("");
        }
    }//GEN-LAST:event_chooseAlgorithmComboBoxActionPerformed

    private void hideAttrsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hideAttrsButtonActionPerformed
        // TODO add your handling code here:
        this.updateMPManagementAttrDefinitionTable();
        this.updateMPManagementMPTable();
    }//GEN-LAST:event_hideAttrsButtonActionPerformed

    private class CalculateCommunitiesSwingWorker extends SwingWorker<Void,Void> {
        private String algorithm;
        private String argument;
        public CalculateCommunitiesSwingWorker(String algorithm, String argument) {
            this.algorithm = algorithm;
            this.argument = argument;
        }
        // doInBackground method is executed in special thread. out of GUI thread.
        // We must NOT manipulate with GUI components
        @Override
        protected Void doInBackground() throws Exception {
            //System.out.print(algorithm);
            pc.computeCommunities(algorithm, argument);
            return null;
        }
        // done method is executed in GUI thread.
        // We can manipulate with GUI components
        @Override
        protected void done() {
            if (isCancelled()) {
                return;
            }
            try {
                get();
                calculateCommunitiesButton.setText("Calculate");
                algorithmProgressBar.setIndeterminate(false);
                sw.cancel(false);
                calculating = false;
                MainView.this.updateCommunitiesTable();
            } catch (InterruptedException e) {
                e.printStackTrace();
            } catch (ExecutionException e) {
                e.printStackTrace();
            }
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>



        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PresentationController prescon = new PresentationController();
                new MainView(prescon).setVisible(true);
            }
        });
    }

    private PresentationController pc;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CommunityManagement;
    private javax.swing.JPanel CommunityPanel1;
    private javax.swing.JPanel CommunityPanel2;
    private javax.swing.JPanel CompareView;
    private javax.swing.JButton LoadCongressButton;
    private javax.swing.JTable MPList1Table;
    private javax.swing.JTable MPList2Table;
    private javax.swing.JScrollPane MPTablePanel;
    private javax.swing.JTable MPsCurrentCongressTable;
    private javax.swing.JTable MPsInCommunityTable;
    private javax.swing.JScrollPane MPsInCommuntiyPanel;
    private javax.swing.JLabel MPsInCurrentCongressLabel;
    private javax.swing.JButton addMPButton;
    private javax.swing.JButton addMPToCommunityButton;
    private javax.swing.JLabel algorithmLabel;
    private javax.swing.JProgressBar algorithmProgressBar;
    private javax.swing.JLabel argumentLabel;
    private javax.swing.JTextField argumentTextField;
    private javax.swing.JScrollPane attrDefPanel;
    private javax.swing.JLabel attrDefinitionsLabel;
    private javax.swing.JPanel attrDefinitionsPanel;
    private javax.swing.JTable attrDefinitionsTable;
    private javax.swing.JPanel buttonsPanel;
    private javax.swing.JButton calculateCommunitiesButton;
    private javax.swing.JComboBox chooseAlgorithmComboBox;
    private javax.swing.JPanel communitiesPanel;
    private javax.swing.JTable communitiesTable;
    private javax.swing.JScrollPane communitiesTablePanel;
    private javax.swing.JList communityList1CommunitiesList;
    private javax.swing.JList communityList2CommunitiesList;
    private javax.swing.JButton compareButton;
    private javax.swing.JPanel congressManagementView;
    private javax.swing.JLabel currentCongressLabel;
    private javax.swing.JTextField currentCongressNameTextField;
    private javax.swing.JLabel currentLoadedCongressLabel;
    private javax.swing.JPanel currentMPsPanel;
    private javax.swing.JTable currentMPsTable;
    private javax.swing.JButton delCommButton;
    private javax.swing.JButton deleteMPButton;
    private javax.swing.JButton deleteMPfromCommunityButton;
    private javax.swing.JRadioButton hideAttrsButton;
    private javax.swing.JLabel labelCommunities;
    private javax.swing.JLabel labelMPs;
    private javax.swing.JLabel list1Label1;
    private javax.swing.JLabel list1Label2;
    private javax.swing.JButton list1LoadPartitionButton;
    private javax.swing.JLabel list1OptionsLabel;
    private javax.swing.JButton list1UseCurrentPartitionButton;
    private javax.swing.JLabel list2Label1;
    private javax.swing.JLabel list2Label2;
    private javax.swing.JButton list2LoadPartitionButton;
    private javax.swing.JLabel list2OptionsLabel;
    private javax.swing.JButton list2UseCurrentPartitionButton;
    private javax.swing.JButton loadCongressButton;
    private javax.swing.JButton loadPartitionButton;
    private javax.swing.JPanel mainView;
    private javax.swing.JTabbedPane mainWindow;
    private javax.swing.JButton modifyAttrDefButton;
    private javax.swing.JButton modifyMPButton;
    private javax.swing.JButton newAttrDefButton;
    private javax.swing.JButton newCommButton;
    private javax.swing.JButton newCongressButton;
    private javax.swing.JButton newPartitionButton;
    private javax.swing.JButton saveCongressButton;
    private javax.swing.JButton savePartitionButton;
    private javax.swing.JScrollPane scrollPaneCommunityList1;
    private javax.swing.JScrollPane scrollPaneCommuntiyList2;
    private javax.swing.JScrollPane scrollPaneMPList1;
    private javax.swing.JScrollPane scrollPaneMPList2;
    private javax.swing.JScrollPane scrollPaneMPsCurrentCongressTable;
    private javax.swing.JButton showMPDataButton;
    private javax.swing.JButton showSelectedMPInfoButton;
    // End of variables declaration//GEN-END:variables
}
